### ISSUE TITLE
下载了导入MyEclipse-Maven时 各种问题！

### ISSUE THREAD

**Issue by yanyinxi** [daniellitoc/xultimate-resource#1]
下载了导入MyEclipse-Maven时 各种问题！

希望能给个导入说明！ 感谢

**Comment by daniellitoc** [comment]
xultimate-resource项目依赖xultimate-toolkit提供的xultimate-core和xultimate-webmvc。

**Comment by daniellitoc** [comment]
还有pom.xml文件中distributionManagement节点，因为我配置了Nexus服务器，所以采用的是我的配置方式，你可以删除distributionManagement节点。

**Comment by ddy88958620** [comment]
@daniellitoc 发现和你的技术路线和关注的东西一直都很类似， 从poading-rose web框架， 到阿里dubbo、分布式、消息中间件、数据库等等，求技术交流，我的微信：dingdaiyang
